### PR TITLE
Skip Pulumi CLI download if runner version satisfies requested CLI version

### LINKED ISSUE #789: Optimization: Skip Download Pulumi CLI when already present
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

With the exception of MacOS and self-hosted runners, Pulumi comes installed on GitHub Actions runners by default. Right now, when a user does not specify a specific version of Pulumi to use, this action defaults to `latest`. Instead, we should use whatever version of Pulumi is installed on the runner, if one exists. This will remove the need to re-download Pulumi for the vast majority of users (anyone who is using Windows or Ubuntu runners).

As described in https://github.com/pulumi/actions/issues/787, this would eliminate `~100MBs` of network traffic. And, detailed in https://github.com/pulumi/actions/issues/674, it would allow the action to be used in the context of where outbound traffic is blocked.

### Affected area/feature

[The `downloadCli` function.](https://github.com/pulumi/actions/blob/master/src/libs/pulumi-cli.ts#L34)

### PR DESCRIPTION
**Pull request by ehafenmaier**
Accidentally closed PR #837 when syncing fork. 

## Original PR
- Add functionality to check GitHub runner for the existence of the Pulumi CLI. 
- If the CLI is already installed on the runner check if the runner CLI version matches the requested version from the action input.
- If runner CLI version matches, skip downloading CLI.
- If CLI not installed on runner or runner CLI does not match requested version, proceed to download CLI

> NOTE: Skipping the CLI download will also skip the outbound network call in the `getVersionObject()` method, which was mentioned in #674 

This resolves #789

### CODE REVIEW

File: src/libs/pulumi-cli.ts [hunk 1]
```diff
@@ -43,6 +57,22 @@ export async function downloadCli(range: string): Promise<void> {
...
   core.info(`Configured range: ${range}`);
 
+  // Check for version of Pulumi CLI installed on the runner
+  const runnerVersion = await getVersion();
+
+  if (runnerVersion) {
+    // Check if runner version matches
+    if (semver.satisfies(runnerVersion, range)) {
+      // If runner version matches, skip downloading CLI by exiting the function
+      core.info(`Pulumi version ${runnerVersion} is already installed on this machine. Skipping downloading.`);
```
Comment (Frassle) [inline src/libs/pulumi-cli.ts:67]:
```suggestion
      core.info(`Pulumi version ${runnerVersion} is already installed on this machine. Skipping download`);
```

File: src/libs/pulumi-cli.ts [hunk 2]
```diff
@@ -43,6 +57,22 @@ export async function downloadCli(range: string): Promise<void> {
...
+    // Check if runner version matches
+    if (semver.satisfies(runnerVersion, range)) {
+      // If runner version matches, skip downloading CLI by exiting the function
+      core.info(`Pulumi version ${runnerVersion} is already installed on this machine. Skipping download`);
+      return;
+    } else {
+      core.info(`Pulumi ${runnerVersion} does not satisfy the desired version ${range}. Proceeding to download`);
+    }
+  } else {
+    core.info('Pulumi is not detected in the PATH. Proceeding to download');
```
Comment (cobraz) [inline src/libs/pulumi-cli.ts:73]: Maybe we should use debug here since we're already sending so many info logs?

```suggestion
    core.debug('Pulumi is not detected in the PATH. Proceeding to download');
```

**Review by cobraz — APPROVED** [review]

File: src/libs/pulumi-cli.ts (hunk 2 above)
Comment (ehafenmaier) [reply src/libs/pulumi-cli.ts:73]: Seems like if this last log message is switched to debug the other two should follow suit since they're all part of the same set of conditions (the outer if and the inner if). Only one of the three will be written out so I guess the question is _are these messages helpful in general or should they only be used for troubleshooting?_

**Review by cobraz — APPROVED** [review]
