### PR TITLE
Fix the `output` command

### LINKED ISSUE #868: Support for 'stack output' command
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

- Add `output` command support to actions

There are multiple scenarios where it's useful to fetch outputs from a stack without having to first call `preview` or `up`.. Reading outputs is fast and has no side effects. while lets you access stack configuration that may not be available anywhere else.

For now we are running `pulumi stack output` as bash code in our pipeline, but this is ugly and hard to maintain. It's also especially annoying as the whole logic to pass outputs and secrets into github workflow is already there and triggered as part of calling `up`/`preview`/`refresh`/.... All it takes is to allow that same logic by itself.

### Affected area/feature

I have looked into solving it myself and it looks like a very subtle change. Please see:
[support for stack output](https://github.com/mikocot/pulumi-actions/commit/a6b265e8c6f22edd930417e5ca5452fb2b45d700)

Yet, for some reason the outputs don't seem to be rendered and I don't really have the test environment and sufficient understanding of underlying system to investigate it. I guess some preconditions might need to be met before `stack.outputs()` is called or some configuration needs to be adapted.

### PR DESCRIPTION
**Pull request by justinvp**
This commit fixes the `output` command to work without having to have a workDir specified to a location with a Pulumi.yaml file. It does this by avoiding calls to `LocalWorkspace.createOrSelectStack`/`selectStack` when the command is `output`. This allows the `output` command to work with any stack, even when there is not a local project available.

Additionally, when the command is `output`, don't attempt to comment on the PR; only actual pulumi operations (like the `up` command) should do that.

Fixes #868

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -54,29 +56,42 @@ const runAction = async (config: Config): Promise<void> => {
...
-    stackOpts.secretsProvider = config.secretsProvider;
+    wsOpts.secretsProvider = config.secretsProvider;
   }
 
-  const stack = await (config.upsert
-    ? LocalWorkspace.createOrSelectStack(stackArgs, stackOpts)
-    : LocalWorkspace.selectStack(stackArgs, stackOpts));
+  // Only initialize `stack` when the command is not `output`.
+  // When the command is `output` we want to avoid the underlying call to `pulumi stack select`,
+  // which requires a Pulumi.yaml file to be present.
```
Comment (justinvp) [inline src/main.ts:66]: The only downside is that we aren't respecting `config.upsert` for the `output` command, so if the stack doesn't exist, it won't be created. I actually think this is ok and the behavior we want for `output`. You really only want to get stack outputs for a stack that exists.

If we felt it was important to keep `upsert` working for the `output` command, we could make a change below on line 131: when calling `outputs = await ws.stackOutputs(config.stackName);` we could wrap that in a try/catch and if it's a `StackNotFoundError` and `config.upsert` is true, we could create the stack and return empty outputs. My preference is to not do this unless we get feedback that it's needed for some scenario.

**Review by Zaid-Ajaj — APPROVED** [review]

**Comment by darena-patrick** [comment]
very excited to try this out - is there a version we should target to provide feedback?
